---
exclude: |
  (?x)^(
    build/ |
    dist/ |
  )$

repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  # Protect secrets using Gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
  # Validate pyproject.toml
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject
  # Supported base hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=10000]
      - id: check-ast
      - id: check-case-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        types: [file]
        files: .(md)$
        args: [--disable, MD013]
  # Add trailing commas to calls and literals.
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  # Lint & format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [--config=pyproject.toml, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [--config=pyproject.toml]
  # Unit tests with pytest
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: python
        additional_dependencies: [pytest, pytest-cov, psycopg2-binary, tabulate, pyyaml, python-dotenv]
        entry: make test
        require_serial: true
        pass_filenames: false
        files: \.py$
