site_name: pg_upsert

repo_name: geocoug/pg_upsert
repo_url: https://github.com/geocoug/pg_upsert

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/lightbulb
        name: Switch to system preference

nav:
  - Home: index.md
  - Examples: examples.md
  - API Reference: pg_upsert.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_root_heading: true
            show_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - tables
  - markdown_include.include:
      base_path: .
